[alerts]
min_alert_threshold = 0.1
vol_multiplier = 1.75
vol_min_points = 6

[[alerts.periods]]
period = "1h"
threshold = 0.2

[[alerts.periods]]
period = "6h"
threshold = 0.5

[[alerts.periods]]
period = "1d"
threshold = 1.0

[[alerts.periods]]
period = "7d"
threshold = 2.5

[[alerts.periods]]
period = "14d"
threshold = 3.5

[[alerts.periods]]
period = "30d"
threshold = 5.0

[logging]
max_bytes = 1000000
backups = 5
